// Deterministic seed data. Kept fixed so UI-automation assertions on counts, titles,
// prices, and stock stay stable across runs.

export const SEED_USERS = [
  {
    name: 'Admin User',
    email: 'admin@demo.com',
    password: 'admin123',
    role: 'admin',
    address: { street: '1 Commerce Way', city: 'Metropolis', postalCode: '10001', country: 'USA' },
  },
  {
    name: 'John Doe',
    email: 'user@demo.com',
    password: 'user123',
    role: 'user',
    address: { street: '42 Market St', city: 'Springfield', postalCode: '55555', country: 'USA' },
  },
];

const img = (category: string) => `/images/${category}.svg`;

export const SEED_PRODUCTS = [
  // Electronics
  {
    name: 'Aurora 4K Monitor',
    description: '27-inch UHD IPS display with HDR10 and a 144Hz refresh rate.',
    price: 329.99,
    category: 'Electronics',
    image: img('electronics'),
    countInStock: 12,
    rating: 4.6,
    numReviews: 84,
    featured: true,
  },
  {
    name: 'Pulse Wireless Charger',
    description: '15W fast Qi charging pad with a non-slip surface.',
    price: 24.99,
    category: 'Electronics',
    image: img('electronics'),
    countInStock: 60,
    rating: 4.2,
    numReviews: 210,
    featured: false,
  },
  {
    name: 'Nimbus USB-C Hub',
    description: '7-in-1 hub: HDMI, 3x USB-A, SD/microSD, and 100W passthrough.',
    price: 49.99,
    category: 'Electronics',
    image: img('electronics'),
    countInStock: 34,
    rating: 4.4,
    numReviews: 57,
    featured: false,
  },
  // Audio
  {
    name: 'Echo Studio Headphones',
    description: 'Over-ear active noise-cancelling headphones with 40h battery.',
    price: 199.99,
    category: 'Audio',
    image: img('audio'),
    countInStock: 20,
    rating: 4.7,
    numReviews: 132,
    featured: true,
  },
  {
    name: 'Bass Drop Earbuds',
    description: 'True wireless earbuds with punchy bass and a compact case.',
    price: 79.99,
    category: 'Audio',
    image: img('audio'),
    countInStock: 45,
    rating: 4.1,
    numReviews: 98,
    featured: false,
  },
  {
    name: 'SoundWave Bluetooth Speaker',
    description: 'Portable IPX7 waterproof speaker with 360° sound.',
    price: 59.99,
    category: 'Audio',
    image: img('audio'),
    countInStock: 0,
    rating: 4.3,
    numReviews: 76,
    featured: false,
  },
  // Wearables
  {
    name: 'Chrono Smartwatch',
    description: 'AMOLED fitness smartwatch with GPS and heart-rate tracking.',
    price: 149.99,
    category: 'Wearables',
    image: img('wearables'),
    countInStock: 18,
    rating: 4.5,
    numReviews: 143,
    featured: true,
  },
  {
    name: 'FitBand Pro Tracker',
    description: 'Slim activity band with sleep tracking and a 10-day battery.',
    price: 89.99,
    category: 'Wearables',
    image: img('wearables'),
    countInStock: 27,
    rating: 4.0,
    numReviews: 61,
    featured: false,
  },
  // Gaming
  {
    name: 'Vortex Mechanical Keyboard',
    description: 'Hot-swappable RGB mechanical keyboard with tactile switches.',
    price: 119.99,
    category: 'Gaming',
    image: img('gaming'),
    countInStock: 22,
    rating: 4.8,
    numReviews: 205,
    featured: true,
  },
  {
    name: 'Raptor Gaming Mouse',
    description: 'Lightweight 26K DPI optical mouse with 8 programmable buttons.',
    price: 44.99,
    category: 'Gaming',
    image: img('gaming'),
    countInStock: 40,
    rating: 4.4,
    numReviews: 118,
    featured: false,
  },
  {
    name: 'Nebula RGB Mousepad',
    description: 'Extended desk mat with per-edge RGB lighting and USB passthrough.',
    price: 19.99,
    category: 'Gaming',
    image: img('gaming'),
    countInStock: 55,
    rating: 4.2,
    numReviews: 44,
    featured: false,
  },
  // Home
  {
    name: 'Brew Master Coffee Maker',
    description: 'Programmable 12-cup drip coffee maker with thermal carafe.',
    price: 89.99,
    category: 'Home',
    image: img('home'),
    countInStock: 15,
    rating: 4.3,
    numReviews: 87,
    featured: false,
  },
  {
    name: 'AirPure Mini Humidifier',
    description: 'Quiet ultrasonic humidifier with ambient night light.',
    price: 34.99,
    category: 'Home',
    image: img('home'),
    countInStock: 38,
    rating: 4.1,
    numReviews: 52,
    featured: false,
  },
  {
    name: 'GlowLite Desk Lamp',
    description: 'Dimmable LED desk lamp with 5 color temperatures and USB port.',
    price: 39.99,
    category: 'Home',
    image: img('home'),
    countInStock: 29,
    rating: 4.5,
    numReviews: 69,
    featured: false,
  },
  // Accessories
  {
    name: 'Nomad Laptop Backpack',
    description: 'Water-resistant 20L backpack with a padded 16-inch laptop sleeve.',
    price: 69.99,
    category: 'Accessories',
    image: img('accessories'),
    countInStock: 25,
    rating: 4.6,
    numReviews: 156,
    featured: true,
  },
  {
    name: 'Vela Leather Wallet',
    description: 'Slim RFID-blocking bifold wallet in full-grain leather.',
    price: 29.99,
    category: 'Accessories',
    image: img('accessories'),
    countInStock: 50,
    rating: 4.4,
    numReviews: 73,
    featured: false,
  },
];
